spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: ms-config-dev
---
spring:
  profiles: test
  application:
    name: ms-config-test
---
spring:
  profiles: prod
  application:
    name: ms-config-prod
  